# Copyright 2018-2020 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[package]
name = "grid-sdk"
version = "0.2.1"
authors = ["Cargill Incorporated"]
description = """\
    Hyperledger Grid is a platform for building supply chain solutions \
    that include distributed ledger components. It provides a growing \
    set of tools that accelerate development for supply chain smart contracts\
    and client interfaces.
"""
homepage = "https://grid.hyperledger.org"
edition = "2018"
license = "Apache-2.0"


[dependencies]
actix-web = { package = "actix-web", version = "3", optional = true }
byteorder = "1"
cfg-if = "0.1"
diesel = { version = "1.0", features = ["r2d2", "serde_json"], optional = true }
diesel_migrations = { version = "1.4", optional = true }
log = { version = "0.4", optional = true }
protobuf = "2.19"
sabre-sdk = { version = "0.5", optional = true }
sawtooth-sdk = { version = "0.4", features = ["transact-compat"], optional=true }
serde = { version = "1.0", features = ["derive"] }
serde_derive = { version = "1.0" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
rust-crypto-wasm = "0.3"
sabre-sdk = "0.5"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rust-crypto = "0.2"
sawtooth-sdk = "0.4"

[build-dependencies]
protoc-rust = "2.14"
glob = "0.2"

[features]
default = []

stable = [
    # The stable feature extends default:
    "default",
    # The following features are stable:
    "location",
    "pike",
    "product",
    "schema",
]

experimental = [
    # The experimental feature extends stable:
    "stable",
    # The following features are experimental:
    "database",
    "rest-api",
    "track-and-trace",
    "workflow"
]

database = ["grid_db", "postgres", "sqlite" ]
location = ["pike", "schema"]
pike = []
product = ["pike", "schema"]
rest-api = []
rest-api-actix-web-3 = ["rest-api", "actix-web"]
schema = ["pike"]
track-and-trace = []

grid_db = ["sawtooth-compat"]
postgres = ["diesel/postgres", "diesel_migrations", "log"]
sawtooth-compat = [
    "sabre-sdk",
    "sawtooth-sdk"
]
sqlite = ["diesel/sqlite", "diesel_migrations"]
workflow = []
